### ISSUE TITLE
Druidi 

### ISSUE THREAD

**Issue by Gwyndrichstein** [Gwyndrichstein/ztraceneostrovy#24]
Druidi ---
- zrušit jim možnost štítu

**Comment by Karg3ths** [comment]
Dle mého naprosto zbytečné řešit v takovém směru, který Ermi nastavil. 

- Jestli rušit štíty, tak buď všem nebo nikomu. Možnost běhat se štítem po lese a abusovat armor má vlastně každý a argument "dělají to jen druidi" mi přijde bezpředmětný.

- Kdyby ten štít zabíjení nedělal pro některé classy více komfortní, tak to lidi ani nenapadne nosit. Na mága ho taky nesháním, protože s talentama smažu všechno bez toho aniž by se mě to pomalu dotklo. Což je něco co druid říct nemůže.

**Comment by Gwyndrichstein** [comment]
Souhlasím s Devilem, zatím to nechám tak a uvidím, jak obří to bude problém do budoucna. Zatím jsem to otestil a nepřijde mi to jako tak hrozný rozdíl oproti jiným meta classám.
