### ISSUE TITLE
Vypnout DF 

### ISSUE THREAD

**Issue by Gwyndrichstein** [Gwyndrichstein/ztraceneostrovy#27]
Vypnout DF ---
- vypnout dungeon finder. aby si tam lidi nenafarmili kdo ví co peněz

**Comment by Karg3ths** [comment]
DF instance IDs:

- Sunken Temple -> **109**
- Blackrock Depths - Prison + Upper -> **230**
- Dire Maul - East, West, North -> **429**
- Lower Blackrock Spire -> **229**
- Scholomance -> **289**
- Stratholme - Main + Service entrance -> **329**

**Comment by Gwyndrichstein** [comment]
Solved.
