### ISSUE TITLE
Kolónia - Vytvoriť porty

### ISSUE THREAD

**Issue by Ion654** [Gwyndrichstein/ztraceneostrovy#44]
**Porty:**
- Vytvoriť portovacie objekty pre domy v kolónii podľa uvedených portov

**V noggite:**
- Pridať ďalšie malé domy do dev lokačky (Zatiaľ nám chýbajú 3 domy na port)
- Urobiť stenu na balkóne Bryanového domu (ako to je u ostatných medium domov)/Popr. sa urobí spawnom

Tabuľka so všetkými portmi IN/OUT a ak majú modely domov balkóny a podobne tak IN/OUT porty i pre to + veľkosť a model domu pre orientačné účely
https://docs.google.com/spreadsheets/d/15h2xN4R3JQmOvxaNE_fHljSKenS2Z2yGI0Ivw6UeIDE/edit?usp=sharing

![kolony](https://user-images.githubusercontent.com/114833550/193427675-e3d058e0-8369-467a-9abe-85aeaebd4554.PNG)

**Comment by Karg3ths** [comment]
- včera jsem připravil template na ty porty v gameojects_template. Neumím počítat a tak jich tam pár zbylo, ale hádám, že ono se to bude eventuelně zase hodit.
- dneska nejsem doma, takže nic nestihnu, ale zítra kouknu na ty scripty a dodělám ty porty
- bylo by fajn hodit tu tabulku s informacema o portech na náš sdílený disk, ať to můžu snadno upravovat a vepsat tam pak info o samotných port itemech

**Comment by Karg3ths** [comment]
- U Bryanova domku by bylo fajn vyměnit i ty dveře. Hodil jsem je tam ve spawnu, aby tam nikdo nelezl.

**Comment by Karg3ths** [comment]
Progress portů
- status odráží jestli jsem už dodělal script
- rozmístění odráží jestli ho už někdo naspawnil
- všechny porty mají hotové goby, jen u většiny jsem ještě nestihl oblétat pozice a naťukat souřadnice
- pokud budete chtít jiný gob, tak mi pište whispy a pokud onen port spawnete, tak prosím taky.

https://docs.google.com/spreadsheets/d/1JQ0izZjvfy75FslLa2SQV9JPuZJ_IxI_YVBDl23zAfk/edit#gid=0
